User.create(first_name: 'Andriana', last_name: 'Peresta', email: 'andriana.peresta@deemaze.com', password: '123456')
User.create(first_name: 'Adriana', last_name: 'Cardoso', email: 'adriana.cardoso@deemaze.com', password: '123456')
User.create(first_name: 'Adriane', last_name: 'Rodrigues', email: 'adriane.rodrigues@deemaze.com', password: '123456')
User.create(first_name: 'António', last_name: 'Marques', email: 'antonio.marques@deemaze.com', password: '123456')
User.create(first_name: 'Bruno', last_name: 'Antoninho', email: 'bruno.antoninho@deemaze.com', password: '123456')
User.create(first_name: 'Carlos', last_name: 'Balsas', email: 'carlos.balsas@deemaze.com', password: '123456')
User.create(first_name: 'Ernest', last_name: 'da Cruz', email: 'ernest.cruz@deemaze.com', password: '123456')
User.create(first_name: 'Joao', last_name: 'Monteiro', email: 'joao.monteiro@deemaze.com', password: '123456')
User.create(first_name: 'João', last_name: 'Oliveira', email: 'joao.oliveira@deemaze.com', password: '123456')
User.create(first_name: 'Maria Inês', last_name: 'Fonseca', email: 'maria.fonseca@deemaze.com', password: '123456')
User.create(first_name: 'Patrícia', last_name: 'Paulo', email: 'patricia.paulo@deemaze.com', password: '123456')
User.create(first_name: 'Paulo', last_name: 'Santos', email: 'paulo.santos@deemaze.com', password: '123456')
User.create(first_name: 'Pedro', last_name: 'Batista', email: 'pedro.batista@deemaze.com', password: '123456')
User.create(first_name: 'Pedro', last_name: 'Santos', email: 'pedro.santos@deemaze.com', password: '123456')
